namespace Common.Dtos.Classes.Arrays
{
    public class ClassWith256Arrays<T>
    {
        public T[] Property1 { get; set; }
        public T[] Property2 { get; set; }
        public T[] Property3 { get; set; }
        public T[] Property4 { get; set; }
        public T[] Property5 { get; set; }
        public T[] Property6 { get; set; }
        public T[] Property7 { get; set; }
        public T[] Property8 { get; set; }
        public T[] Property9 { get; set; }
        public T[] Property10 { get; set; }
        public T[] Property11 { get; set; }
        public T[] Property12 { get; set; }
        public T[] Property13 { get; set; }
        public T[] Property14 { get; set; }
        public T[] Property15 { get; set; }
        public T[] Property16 { get; set; }
        public T[] Property17 { get; set; }
        public T[] Property18 { get; set; }
        public T[] Property19 { get; set; }
        public T[] Property20 { get; set; }
        public T[] Property21 { get; set; }
        public T[] Property22 { get; set; }
        public T[] Property23 { get; set; }
        public T[] Property24 { get; set; }
        public T[] Property25 { get; set; }
        public T[] Property26 { get; set; }
        public T[] Property27 { get; set; }
        public T[] Property28 { get; set; }
        public T[] Property29 { get; set; }
        public T[] Property30 { get; set; }
        public T[] Property31 { get; set; }
        public T[] Property32 { get; set; }
        public T[] Property33 { get; set; }
        public T[] Property34 { get; set; }
        public T[] Property35 { get; set; }
        public T[] Property36 { get; set; }
        public T[] Property37 { get; set; }
        public T[] Property38 { get; set; }
        public T[] Property39 { get; set; }
        public T[] Property40 { get; set; }
        public T[] Property41 { get; set; }
        public T[] Property42 { get; set; }
        public T[] Property43 { get; set; }
        public T[] Property44 { get; set; }
        public T[] Property45 { get; set; }
        public T[] Property46 { get; set; }
        public T[] Property47 { get; set; }
        public T[] Property48 { get; set; }
        public T[] Property49 { get; set; }
        public T[] Property50 { get; set; }
        public T[] Property51 { get; set; }
        public T[] Property52 { get; set; }
        public T[] Property53 { get; set; }
        public T[] Property54 { get; set; }
        public T[] Property55 { get; set; }
        public T[] Property56 { get; set; }
        public T[] Property57 { get; set; }
        public T[] Property58 { get; set; }
        public T[] Property59 { get; set; }
        public T[] Property60 { get; set; }
        public T[] Property61 { get; set; }
        public T[] Property62 { get; set; }
        public T[] Property63 { get; set; }
        public T[] Property64 { get; set; }
        public T[] Property65 { get; set; }
        public T[] Property66 { get; set; }
        public T[] Property67 { get; set; }
        public T[] Property68 { get; set; }
        public T[] Property69 { get; set; }
        public T[] Property70 { get; set; }
        public T[] Property71 { get; set; }
        public T[] Property72 { get; set; }
        public T[] Property73 { get; set; }
        public T[] Property74 { get; set; }
        public T[] Property75 { get; set; }
        public T[] Property76 { get; set; }
        public T[] Property77 { get; set; }
        public T[] Property78 { get; set; }
        public T[] Property79 { get; set; }
        public T[] Property80 { get; set; }
        public T[] Property81 { get; set; }
        public T[] Property82 { get; set; }
        public T[] Property83 { get; set; }
        public T[] Property84 { get; set; }
        public T[] Property85 { get; set; }
        public T[] Property86 { get; set; }
        public T[] Property87 { get; set; }
        public T[] Property88 { get; set; }
        public T[] Property89 { get; set; }
        public T[] Property90 { get; set; }
        public T[] Property91 { get; set; }
        public T[] Property92 { get; set; }
        public T[] Property93 { get; set; }
        public T[] Property94 { get; set; }
        public T[] Property95 { get; set; }
        public T[] Property96 { get; set; }
        public T[] Property97 { get; set; }
        public T[] Property98 { get; set; }
        public T[] Property99 { get; set; }
        public T[] Property100 { get; set; }
        public T[] Property101 { get; set; }
        public T[] Property102 { get; set; }
        public T[] Property103 { get; set; }
        public T[] Property104 { get; set; }
        public T[] Property105 { get; set; }
        public T[] Property106 { get; set; }
        public T[] Property107 { get; set; }
        public T[] Property108 { get; set; }
        public T[] Property109 { get; set; }
        public T[] Property110 { get; set; }
        public T[] Property111 { get; set; }
        public T[] Property112 { get; set; }
        public T[] Property113 { get; set; }
        public T[] Property114 { get; set; }
        public T[] Property115 { get; set; }
        public T[] Property116 { get; set; }
        public T[] Property117 { get; set; }
        public T[] Property118 { get; set; }
        public T[] Property119 { get; set; }
        public T[] Property120 { get; set; }
        public T[] Property121 { get; set; }
        public T[] Property122 { get; set; }
        public T[] Property123 { get; set; }
        public T[] Property124 { get; set; }
        public T[] Property125 { get; set; }
        public T[] Property126 { get; set; }
        public T[] Property127 { get; set; }
        public T[] Property128 { get; set; }
        public T[] Property129 { get; set; }
        public T[] Property130 { get; set; }
        public T[] Property131 { get; set; }
        public T[] Property132 { get; set; }
        public T[] Property133 { get; set; }
        public T[] Property134 { get; set; }
        public T[] Property135 { get; set; }
        public T[] Property136 { get; set; }
        public T[] Property137 { get; set; }
        public T[] Property138 { get; set; }
        public T[] Property139 { get; set; }
        public T[] Property140 { get; set; }
        public T[] Property141 { get; set; }
        public T[] Property142 { get; set; }
        public T[] Property143 { get; set; }
        public T[] Property144 { get; set; }
        public T[] Property145 { get; set; }
        public T[] Property146 { get; set; }
        public T[] Property147 { get; set; }
        public T[] Property148 { get; set; }
        public T[] Property149 { get; set; }
        public T[] Property150 { get; set; }
        public T[] Property151 { get; set; }
        public T[] Property152 { get; set; }
        public T[] Property153 { get; set; }
        public T[] Property154 { get; set; }
        public T[] Property155 { get; set; }
        public T[] Property156 { get; set; }
        public T[] Property157 { get; set; }
        public T[] Property158 { get; set; }
        public T[] Property159 { get; set; }
        public T[] Property160 { get; set; }
        public T[] Property161 { get; set; }
        public T[] Property162 { get; set; }
        public T[] Property163 { get; set; }
        public T[] Property164 { get; set; }
        public T[] Property165 { get; set; }
        public T[] Property166 { get; set; }
        public T[] Property167 { get; set; }
        public T[] Property168 { get; set; }
        public T[] Property169 { get; set; }
        public T[] Property170 { get; set; }
        public T[] Property171 { get; set; }
        public T[] Property172 { get; set; }
        public T[] Property173 { get; set; }
        public T[] Property174 { get; set; }
        public T[] Property175 { get; set; }
        public T[] Property176 { get; set; }
        public T[] Property177 { get; set; }
        public T[] Property178 { get; set; }
        public T[] Property179 { get; set; }
        public T[] Property180 { get; set; }
        public T[] Property181 { get; set; }
        public T[] Property182 { get; set; }
        public T[] Property183 { get; set; }
        public T[] Property184 { get; set; }
        public T[] Property185 { get; set; }
        public T[] Property186 { get; set; }
        public T[] Property187 { get; set; }
        public T[] Property188 { get; set; }
        public T[] Property189 { get; set; }
        public T[] Property190 { get; set; }
        public T[] Property191 { get; set; }
        public T[] Property192 { get; set; }
        public T[] Property193 { get; set; }
        public T[] Property194 { get; set; }
        public T[] Property195 { get; set; }
        public T[] Property196 { get; set; }
        public T[] Property197 { get; set; }
        public T[] Property198 { get; set; }
        public T[] Property199 { get; set; }
        public T[] Property200 { get; set; }
        public T[] Property201 { get; set; }
        public T[] Property202 { get; set; }
        public T[] Property203 { get; set; }
        public T[] Property204 { get; set; }
        public T[] Property205 { get; set; }
        public T[] Property206 { get; set; }
        public T[] Property207 { get; set; }
        public T[] Property208 { get; set; }
        public T[] Property209 { get; set; }
        public T[] Property210 { get; set; }
        public T[] Property211 { get; set; }
        public T[] Property212 { get; set; }
        public T[] Property213 { get; set; }
        public T[] Property214 { get; set; }
        public T[] Property215 { get; set; }
        public T[] Property216 { get; set; }
        public T[] Property217 { get; set; }
        public T[] Property218 { get; set; }
        public T[] Property219 { get; set; }
        public T[] Property220 { get; set; }
        public T[] Property221 { get; set; }
        public T[] Property222 { get; set; }
        public T[] Property223 { get; set; }
        public T[] Property224 { get; set; }
        public T[] Property225 { get; set; }
        public T[] Property226 { get; set; }
        public T[] Property227 { get; set; }
        public T[] Property228 { get; set; }
        public T[] Property229 { get; set; }
        public T[] Property230 { get; set; }
        public T[] Property231 { get; set; }
        public T[] Property232 { get; set; }
        public T[] Property233 { get; set; }
        public T[] Property234 { get; set; }
        public T[] Property235 { get; set; }
        public T[] Property236 { get; set; }
        public T[] Property237 { get; set; }
        public T[] Property238 { get; set; }
        public T[] Property239 { get; set; }
        public T[] Property240 { get; set; }
        public T[] Property241 { get; set; }
        public T[] Property242 { get; set; }
        public T[] Property243 { get; set; }
        public T[] Property244 { get; set; }
        public T[] Property245 { get; set; }
        public T[] Property246 { get; set; }
        public T[] Property247 { get; set; }
        public T[] Property248 { get; set; }
        public T[] Property249 { get; set; }
        public T[] Property250 { get; set; }
        public T[] Property251 { get; set; }
        public T[] Property252 { get; set; }
        public T[] Property253 { get; set; }
        public T[] Property254 { get; set; }
        public T[] Property255 { get; set; }
        public T[] Property256 { get; set; }
    }
}
