using System.Collections.Generic;

namespace Common.Dtos.Classes.Lists
{
    public class ClassWith256Lists<T>
    {
        public List<T> Property1 { get; set; }
        public List<T> Property2 { get; set; }
        public List<T> Property3 { get; set; }
        public List<T> Property4 { get; set; }
        public List<T> Property5 { get; set; }
        public List<T> Property6 { get; set; }
        public List<T> Property7 { get; set; }
        public List<T> Property8 { get; set; }
        public List<T> Property9 { get; set; }
        public List<T> Property10 { get; set; }
        public List<T> Property11 { get; set; }
        public List<T> Property12 { get; set; }
        public List<T> Property13 { get; set; }
        public List<T> Property14 { get; set; }
        public List<T> Property15 { get; set; }
        public List<T> Property16 { get; set; }
        public List<T> Property17 { get; set; }
        public List<T> Property18 { get; set; }
        public List<T> Property19 { get; set; }
        public List<T> Property20 { get; set; }
        public List<T> Property21 { get; set; }
        public List<T> Property22 { get; set; }
        public List<T> Property23 { get; set; }
        public List<T> Property24 { get; set; }
        public List<T> Property25 { get; set; }
        public List<T> Property26 { get; set; }
        public List<T> Property27 { get; set; }
        public List<T> Property28 { get; set; }
        public List<T> Property29 { get; set; }
        public List<T> Property30 { get; set; }
        public List<T> Property31 { get; set; }
        public List<T> Property32 { get; set; }
        public List<T> Property33 { get; set; }
        public List<T> Property34 { get; set; }
        public List<T> Property35 { get; set; }
        public List<T> Property36 { get; set; }
        public List<T> Property37 { get; set; }
        public List<T> Property38 { get; set; }
        public List<T> Property39 { get; set; }
        public List<T> Property40 { get; set; }
        public List<T> Property41 { get; set; }
        public List<T> Property42 { get; set; }
        public List<T> Property43 { get; set; }
        public List<T> Property44 { get; set; }
        public List<T> Property45 { get; set; }
        public List<T> Property46 { get; set; }
        public List<T> Property47 { get; set; }
        public List<T> Property48 { get; set; }
        public List<T> Property49 { get; set; }
        public List<T> Property50 { get; set; }
        public List<T> Property51 { get; set; }
        public List<T> Property52 { get; set; }
        public List<T> Property53 { get; set; }
        public List<T> Property54 { get; set; }
        public List<T> Property55 { get; set; }
        public List<T> Property56 { get; set; }
        public List<T> Property57 { get; set; }
        public List<T> Property58 { get; set; }
        public List<T> Property59 { get; set; }
        public List<T> Property60 { get; set; }
        public List<T> Property61 { get; set; }
        public List<T> Property62 { get; set; }
        public List<T> Property63 { get; set; }
        public List<T> Property64 { get; set; }
        public List<T> Property65 { get; set; }
        public List<T> Property66 { get; set; }
        public List<T> Property67 { get; set; }
        public List<T> Property68 { get; set; }
        public List<T> Property69 { get; set; }
        public List<T> Property70 { get; set; }
        public List<T> Property71 { get; set; }
        public List<T> Property72 { get; set; }
        public List<T> Property73 { get; set; }
        public List<T> Property74 { get; set; }
        public List<T> Property75 { get; set; }
        public List<T> Property76 { get; set; }
        public List<T> Property77 { get; set; }
        public List<T> Property78 { get; set; }
        public List<T> Property79 { get; set; }
        public List<T> Property80 { get; set; }
        public List<T> Property81 { get; set; }
        public List<T> Property82 { get; set; }
        public List<T> Property83 { get; set; }
        public List<T> Property84 { get; set; }
        public List<T> Property85 { get; set; }
        public List<T> Property86 { get; set; }
        public List<T> Property87 { get; set; }
        public List<T> Property88 { get; set; }
        public List<T> Property89 { get; set; }
        public List<T> Property90 { get; set; }
        public List<T> Property91 { get; set; }
        public List<T> Property92 { get; set; }
        public List<T> Property93 { get; set; }
        public List<T> Property94 { get; set; }
        public List<T> Property95 { get; set; }
        public List<T> Property96 { get; set; }
        public List<T> Property97 { get; set; }
        public List<T> Property98 { get; set; }
        public List<T> Property99 { get; set; }
        public List<T> Property100 { get; set; }
        public List<T> Property101 { get; set; }
        public List<T> Property102 { get; set; }
        public List<T> Property103 { get; set; }
        public List<T> Property104 { get; set; }
        public List<T> Property105 { get; set; }
        public List<T> Property106 { get; set; }
        public List<T> Property107 { get; set; }
        public List<T> Property108 { get; set; }
        public List<T> Property109 { get; set; }
        public List<T> Property110 { get; set; }
        public List<T> Property111 { get; set; }
        public List<T> Property112 { get; set; }
        public List<T> Property113 { get; set; }
        public List<T> Property114 { get; set; }
        public List<T> Property115 { get; set; }
        public List<T> Property116 { get; set; }
        public List<T> Property117 { get; set; }
        public List<T> Property118 { get; set; }
        public List<T> Property119 { get; set; }
        public List<T> Property120 { get; set; }
        public List<T> Property121 { get; set; }
        public List<T> Property122 { get; set; }
        public List<T> Property123 { get; set; }
        public List<T> Property124 { get; set; }
        public List<T> Property125 { get; set; }
        public List<T> Property126 { get; set; }
        public List<T> Property127 { get; set; }
        public List<T> Property128 { get; set; }
        public List<T> Property129 { get; set; }
        public List<T> Property130 { get; set; }
        public List<T> Property131 { get; set; }
        public List<T> Property132 { get; set; }
        public List<T> Property133 { get; set; }
        public List<T> Property134 { get; set; }
        public List<T> Property135 { get; set; }
        public List<T> Property136 { get; set; }
        public List<T> Property137 { get; set; }
        public List<T> Property138 { get; set; }
        public List<T> Property139 { get; set; }
        public List<T> Property140 { get; set; }
        public List<T> Property141 { get; set; }
        public List<T> Property142 { get; set; }
        public List<T> Property143 { get; set; }
        public List<T> Property144 { get; set; }
        public List<T> Property145 { get; set; }
        public List<T> Property146 { get; set; }
        public List<T> Property147 { get; set; }
        public List<T> Property148 { get; set; }
        public List<T> Property149 { get; set; }
        public List<T> Property150 { get; set; }
        public List<T> Property151 { get; set; }
        public List<T> Property152 { get; set; }
        public List<T> Property153 { get; set; }
        public List<T> Property154 { get; set; }
        public List<T> Property155 { get; set; }
        public List<T> Property156 { get; set; }
        public List<T> Property157 { get; set; }
        public List<T> Property158 { get; set; }
        public List<T> Property159 { get; set; }
        public List<T> Property160 { get; set; }
        public List<T> Property161 { get; set; }
        public List<T> Property162 { get; set; }
        public List<T> Property163 { get; set; }
        public List<T> Property164 { get; set; }
        public List<T> Property165 { get; set; }
        public List<T> Property166 { get; set; }
        public List<T> Property167 { get; set; }
        public List<T> Property168 { get; set; }
        public List<T> Property169 { get; set; }
        public List<T> Property170 { get; set; }
        public List<T> Property171 { get; set; }
        public List<T> Property172 { get; set; }
        public List<T> Property173 { get; set; }
        public List<T> Property174 { get; set; }
        public List<T> Property175 { get; set; }
        public List<T> Property176 { get; set; }
        public List<T> Property177 { get; set; }
        public List<T> Property178 { get; set; }
        public List<T> Property179 { get; set; }
        public List<T> Property180 { get; set; }
        public List<T> Property181 { get; set; }
        public List<T> Property182 { get; set; }
        public List<T> Property183 { get; set; }
        public List<T> Property184 { get; set; }
        public List<T> Property185 { get; set; }
        public List<T> Property186 { get; set; }
        public List<T> Property187 { get; set; }
        public List<T> Property188 { get; set; }
        public List<T> Property189 { get; set; }
        public List<T> Property190 { get; set; }
        public List<T> Property191 { get; set; }
        public List<T> Property192 { get; set; }
        public List<T> Property193 { get; set; }
        public List<T> Property194 { get; set; }
        public List<T> Property195 { get; set; }
        public List<T> Property196 { get; set; }
        public List<T> Property197 { get; set; }
        public List<T> Property198 { get; set; }
        public List<T> Property199 { get; set; }
        public List<T> Property200 { get; set; }
        public List<T> Property201 { get; set; }
        public List<T> Property202 { get; set; }
        public List<T> Property203 { get; set; }
        public List<T> Property204 { get; set; }
        public List<T> Property205 { get; set; }
        public List<T> Property206 { get; set; }
        public List<T> Property207 { get; set; }
        public List<T> Property208 { get; set; }
        public List<T> Property209 { get; set; }
        public List<T> Property210 { get; set; }
        public List<T> Property211 { get; set; }
        public List<T> Property212 { get; set; }
        public List<T> Property213 { get; set; }
        public List<T> Property214 { get; set; }
        public List<T> Property215 { get; set; }
        public List<T> Property216 { get; set; }
        public List<T> Property217 { get; set; }
        public List<T> Property218 { get; set; }
        public List<T> Property219 { get; set; }
        public List<T> Property220 { get; set; }
        public List<T> Property221 { get; set; }
        public List<T> Property222 { get; set; }
        public List<T> Property223 { get; set; }
        public List<T> Property224 { get; set; }
        public List<T> Property225 { get; set; }
        public List<T> Property226 { get; set; }
        public List<T> Property227 { get; set; }
        public List<T> Property228 { get; set; }
        public List<T> Property229 { get; set; }
        public List<T> Property230 { get; set; }
        public List<T> Property231 { get; set; }
        public List<T> Property232 { get; set; }
        public List<T> Property233 { get; set; }
        public List<T> Property234 { get; set; }
        public List<T> Property235 { get; set; }
        public List<T> Property236 { get; set; }
        public List<T> Property237 { get; set; }
        public List<T> Property238 { get; set; }
        public List<T> Property239 { get; set; }
        public List<T> Property240 { get; set; }
        public List<T> Property241 { get; set; }
        public List<T> Property242 { get; set; }
        public List<T> Property243 { get; set; }
        public List<T> Property244 { get; set; }
        public List<T> Property245 { get; set; }
        public List<T> Property246 { get; set; }
        public List<T> Property247 { get; set; }
        public List<T> Property248 { get; set; }
        public List<T> Property249 { get; set; }
        public List<T> Property250 { get; set; }
        public List<T> Property251 { get; set; }
        public List<T> Property252 { get; set; }
        public List<T> Property253 { get; set; }
        public List<T> Property254 { get; set; }
        public List<T> Property255 { get; set; }
        public List<T> Property256 { get; set; }
    }
}
