namespace Common.Dtos.Classes.Integers
{
    public class ClassWith128Ints
    {
        public int Property1 { get; set; }
        public int Property2 { get; set; }
        public int Property3 { get; set; }
        public int Property4 { get; set; }
        public int Property5 { get; set; }
        public int Property6 { get; set; }
        public int Property7 { get; set; }
        public int Property8 { get; set; }
        public int Property9 { get; set; }
        public int Property10 { get; set; }
        public int Property11 { get; set; }
        public int Property12 { get; set; }
        public int Property13 { get; set; }
        public int Property14 { get; set; }
        public int Property15 { get; set; }
        public int Property16 { get; set; }
        public int Property17 { get; set; }
        public int Property18 { get; set; }
        public int Property19 { get; set; }
        public int Property20 { get; set; }
        public int Property21 { get; set; }
        public int Property22 { get; set; }
        public int Property23 { get; set; }
        public int Property24 { get; set; }
        public int Property25 { get; set; }
        public int Property26 { get; set; }
        public int Property27 { get; set; }
        public int Property28 { get; set; }
        public int Property29 { get; set; }
        public int Property30 { get; set; }
        public int Property31 { get; set; }
        public int Property32 { get; set; }
        public int Property33 { get; set; }
        public int Property34 { get; set; }
        public int Property35 { get; set; }
        public int Property36 { get; set; }
        public int Property37 { get; set; }
        public int Property38 { get; set; }
        public int Property39 { get; set; }
        public int Property40 { get; set; }
        public int Property41 { get; set; }
        public int Property42 { get; set; }
        public int Property43 { get; set; }
        public int Property44 { get; set; }
        public int Property45 { get; set; }
        public int Property46 { get; set; }
        public int Property47 { get; set; }
        public int Property48 { get; set; }
        public int Property49 { get; set; }
        public int Property50 { get; set; }
        public int Property51 { get; set; }
        public int Property52 { get; set; }
        public int Property53 { get; set; }
        public int Property54 { get; set; }
        public int Property55 { get; set; }
        public int Property56 { get; set; }
        public int Property57 { get; set; }
        public int Property58 { get; set; }
        public int Property59 { get; set; }
        public int Property60 { get; set; }
        public int Property61 { get; set; }
        public int Property62 { get; set; }
        public int Property63 { get; set; }
        public int Property64 { get; set; }
        public int Property65 { get; set; }
        public int Property66 { get; set; }
        public int Property67 { get; set; }
        public int Property68 { get; set; }
        public int Property69 { get; set; }
        public int Property70 { get; set; }
        public int Property71 { get; set; }
        public int Property72 { get; set; }
        public int Property73 { get; set; }
        public int Property74 { get; set; }
        public int Property75 { get; set; }
        public int Property76 { get; set; }
        public int Property77 { get; set; }
        public int Property78 { get; set; }
        public int Property79 { get; set; }
        public int Property80 { get; set; }
        public int Property81 { get; set; }
        public int Property82 { get; set; }
        public int Property83 { get; set; }
        public int Property84 { get; set; }
        public int Property85 { get; set; }
        public int Property86 { get; set; }
        public int Property87 { get; set; }
        public int Property88 { get; set; }
        public int Property89 { get; set; }
        public int Property90 { get; set; }
        public int Property91 { get; set; }
        public int Property92 { get; set; }
        public int Property93 { get; set; }
        public int Property94 { get; set; }
        public int Property95 { get; set; }
        public int Property96 { get; set; }
        public int Property97 { get; set; }
        public int Property98 { get; set; }
        public int Property99 { get; set; }
        public int Property100 { get; set; }
        public int Property101 { get; set; }
        public int Property102 { get; set; }
        public int Property103 { get; set; }
        public int Property104 { get; set; }
        public int Property105 { get; set; }
        public int Property106 { get; set; }
        public int Property107 { get; set; }
        public int Property108 { get; set; }
        public int Property109 { get; set; }
        public int Property110 { get; set; }
        public int Property111 { get; set; }
        public int Property112 { get; set; }
        public int Property113 { get; set; }
        public int Property114 { get; set; }
        public int Property115 { get; set; }
        public int Property116 { get; set; }
        public int Property117 { get; set; }
        public int Property118 { get; set; }
        public int Property119 { get; set; }
        public int Property120 { get; set; }
        public int Property121 { get; set; }
        public int Property122 { get; set; }
        public int Property123 { get; set; }
        public int Property124 { get; set; }
        public int Property125 { get; set; }
        public int Property126 { get; set; }
        public int Property127 { get; set; }
        public int Property128 { get; set; }

    }
}
