namespace Common.Dtos.Classes.Integers
{
    public class ClassWith256Ints
    {
        public int Property1 { get; set; }
        public int Property2 { get; set; }
        public int Property3 { get; set; }
        public int Property4 { get; set; }
        public int Property5 { get; set; }
        public int Property6 { get; set; }
        public int Property7 { get; set; }
        public int Property8 { get; set; }
        public int Property9 { get; set; }
        public int Property10 { get; set; }
        public int Property11 { get; set; }
        public int Property12 { get; set; }
        public int Property13 { get; set; }
        public int Property14 { get; set; }
        public int Property15 { get; set; }
        public int Property16 { get; set; }
        public int Property17 { get; set; }
        public int Property18 { get; set; }
        public int Property19 { get; set; }
        public int Property20 { get; set; }
        public int Property21 { get; set; }
        public int Property22 { get; set; }
        public int Property23 { get; set; }
        public int Property24 { get; set; }
        public int Property25 { get; set; }
        public int Property26 { get; set; }
        public int Property27 { get; set; }
        public int Property28 { get; set; }
        public int Property29 { get; set; }
        public int Property30 { get; set; }
        public int Property31 { get; set; }
        public int Property32 { get; set; }
        public int Property33 { get; set; }
        public int Property34 { get; set; }
        public int Property35 { get; set; }
        public int Property36 { get; set; }
        public int Property37 { get; set; }
        public int Property38 { get; set; }
        public int Property39 { get; set; }
        public int Property40 { get; set; }
        public int Property41 { get; set; }
        public int Property42 { get; set; }
        public int Property43 { get; set; }
        public int Property44 { get; set; }
        public int Property45 { get; set; }
        public int Property46 { get; set; }
        public int Property47 { get; set; }
        public int Property48 { get; set; }
        public int Property49 { get; set; }
        public int Property50 { get; set; }
        public int Property51 { get; set; }
        public int Property52 { get; set; }
        public int Property53 { get; set; }
        public int Property54 { get; set; }
        public int Property55 { get; set; }
        public int Property56 { get; set; }
        public int Property57 { get; set; }
        public int Property58 { get; set; }
        public int Property59 { get; set; }
        public int Property60 { get; set; }
        public int Property61 { get; set; }
        public int Property62 { get; set; }
        public int Property63 { get; set; }
        public int Property64 { get; set; }
        public int Property65 { get; set; }
        public int Property66 { get; set; }
        public int Property67 { get; set; }
        public int Property68 { get; set; }
        public int Property69 { get; set; }
        public int Property70 { get; set; }
        public int Property71 { get; set; }
        public int Property72 { get; set; }
        public int Property73 { get; set; }
        public int Property74 { get; set; }
        public int Property75 { get; set; }
        public int Property76 { get; set; }
        public int Property77 { get; set; }
        public int Property78 { get; set; }
        public int Property79 { get; set; }
        public int Property80 { get; set; }
        public int Property81 { get; set; }
        public int Property82 { get; set; }
        public int Property83 { get; set; }
        public int Property84 { get; set; }
        public int Property85 { get; set; }
        public int Property86 { get; set; }
        public int Property87 { get; set; }
        public int Property88 { get; set; }
        public int Property89 { get; set; }
        public int Property90 { get; set; }
        public int Property91 { get; set; }
        public int Property92 { get; set; }
        public int Property93 { get; set; }
        public int Property94 { get; set; }
        public int Property95 { get; set; }
        public int Property96 { get; set; }
        public int Property97 { get; set; }
        public int Property98 { get; set; }
        public int Property99 { get; set; }
        public int Property100 { get; set; }
        public int Property101 { get; set; }
        public int Property102 { get; set; }
        public int Property103 { get; set; }
        public int Property104 { get; set; }
        public int Property105 { get; set; }
        public int Property106 { get; set; }
        public int Property107 { get; set; }
        public int Property108 { get; set; }
        public int Property109 { get; set; }
        public int Property110 { get; set; }
        public int Property111 { get; set; }
        public int Property112 { get; set; }
        public int Property113 { get; set; }
        public int Property114 { get; set; }
        public int Property115 { get; set; }
        public int Property116 { get; set; }
        public int Property117 { get; set; }
        public int Property118 { get; set; }
        public int Property119 { get; set; }
        public int Property120 { get; set; }
        public int Property121 { get; set; }
        public int Property122 { get; set; }
        public int Property123 { get; set; }
        public int Property124 { get; set; }
        public int Property125 { get; set; }
        public int Property126 { get; set; }
        public int Property127 { get; set; }
        public int Property128 { get; set; }
        public int Property129 { get; set; }
        public int Property130 { get; set; }
        public int Property131 { get; set; }
        public int Property132 { get; set; }
        public int Property133 { get; set; }
        public int Property134 { get; set; }
        public int Property135 { get; set; }
        public int Property136 { get; set; }
        public int Property137 { get; set; }
        public int Property138 { get; set; }
        public int Property139 { get; set; }
        public int Property140 { get; set; }
        public int Property141 { get; set; }
        public int Property142 { get; set; }
        public int Property143 { get; set; }
        public int Property144 { get; set; }
        public int Property145 { get; set; }
        public int Property146 { get; set; }
        public int Property147 { get; set; }
        public int Property148 { get; set; }
        public int Property149 { get; set; }
        public int Property150 { get; set; }
        public int Property151 { get; set; }
        public int Property152 { get; set; }
        public int Property153 { get; set; }
        public int Property154 { get; set; }
        public int Property155 { get; set; }
        public int Property156 { get; set; }
        public int Property157 { get; set; }
        public int Property158 { get; set; }
        public int Property159 { get; set; }
        public int Property160 { get; set; }
        public int Property161 { get; set; }
        public int Property162 { get; set; }
        public int Property163 { get; set; }
        public int Property164 { get; set; }
        public int Property165 { get; set; }
        public int Property166 { get; set; }
        public int Property167 { get; set; }
        public int Property168 { get; set; }
        public int Property169 { get; set; }
        public int Property170 { get; set; }
        public int Property171 { get; set; }
        public int Property172 { get; set; }
        public int Property173 { get; set; }
        public int Property174 { get; set; }
        public int Property175 { get; set; }
        public int Property176 { get; set; }
        public int Property177 { get; set; }
        public int Property178 { get; set; }
        public int Property179 { get; set; }
        public int Property180 { get; set; }
        public int Property181 { get; set; }
        public int Property182 { get; set; }
        public int Property183 { get; set; }
        public int Property184 { get; set; }
        public int Property185 { get; set; }
        public int Property186 { get; set; }
        public int Property187 { get; set; }
        public int Property188 { get; set; }
        public int Property189 { get; set; }
        public int Property190 { get; set; }
        public int Property191 { get; set; }
        public int Property192 { get; set; }
        public int Property193 { get; set; }
        public int Property194 { get; set; }
        public int Property195 { get; set; }
        public int Property196 { get; set; }
        public int Property197 { get; set; }
        public int Property198 { get; set; }
        public int Property199 { get; set; }
        public int Property200 { get; set; }
        public int Property201 { get; set; }
        public int Property202 { get; set; }
        public int Property203 { get; set; }
        public int Property204 { get; set; }
        public int Property205 { get; set; }
        public int Property206 { get; set; }
        public int Property207 { get; set; }
        public int Property208 { get; set; }
        public int Property209 { get; set; }
        public int Property210 { get; set; }
        public int Property211 { get; set; }
        public int Property212 { get; set; }
        public int Property213 { get; set; }
        public int Property214 { get; set; }
        public int Property215 { get; set; }
        public int Property216 { get; set; }
        public int Property217 { get; set; }
        public int Property218 { get; set; }
        public int Property219 { get; set; }
        public int Property220 { get; set; }
        public int Property221 { get; set; }
        public int Property222 { get; set; }
        public int Property223 { get; set; }
        public int Property224 { get; set; }
        public int Property225 { get; set; }
        public int Property226 { get; set; }
        public int Property227 { get; set; }
        public int Property228 { get; set; }
        public int Property229 { get; set; }
        public int Property230 { get; set; }
        public int Property231 { get; set; }
        public int Property232 { get; set; }
        public int Property233 { get; set; }
        public int Property234 { get; set; }
        public int Property235 { get; set; }
        public int Property236 { get; set; }
        public int Property237 { get; set; }
        public int Property238 { get; set; }
        public int Property239 { get; set; }
        public int Property240 { get; set; }
        public int Property241 { get; set; }
        public int Property242 { get; set; }
        public int Property243 { get; set; }
        public int Property244 { get; set; }
        public int Property245 { get; set; }
        public int Property246 { get; set; }
        public int Property247 { get; set; }
        public int Property248 { get; set; }
        public int Property249 { get; set; }
        public int Property250 { get; set; }
        public int Property251 { get; set; }
        public int Property252 { get; set; }
        public int Property253 { get; set; }
        public int Property254 { get; set; }
        public int Property255 { get; set; }
        public int Property256 { get; set; }
    }
}
