namespace Common.Dtos.Classes.Integers
{
    public class ClassWith64Ints
    {
        public int Property1 { get; set; }
        public int Property2 { get; set; }
        public int Property3 { get; set; }
        public int Property4 { get; set; }
        public int Property5 { get; set; }
        public int Property6 { get; set; }
        public int Property7 { get; set; }
        public int Property8 { get; set; }
        public int Property9 { get; set; }
        public int Property10 { get; set; }
        public int Property11 { get; set; }
        public int Property12 { get; set; }
        public int Property13 { get; set; }
        public int Property14 { get; set; }
        public int Property15 { get; set; }
        public int Property16 { get; set; }
        public int Property17 { get; set; }
        public int Property18 { get; set; }
        public int Property19 { get; set; }
        public int Property20 { get; set; }
        public int Property21 { get; set; }
        public int Property22 { get; set; }
        public int Property23 { get; set; }
        public int Property24 { get; set; }
        public int Property25 { get; set; }
        public int Property26 { get; set; }
        public int Property27 { get; set; }
        public int Property28 { get; set; }
        public int Property29 { get; set; }
        public int Property30 { get; set; }
        public int Property31 { get; set; }
        public int Property32 { get; set; }
        public int Property33 { get; set; }
        public int Property34 { get; set; }
        public int Property35 { get; set; }
        public int Property36 { get; set; }
        public int Property37 { get; set; }
        public int Property38 { get; set; }
        public int Property39 { get; set; }
        public int Property40 { get; set; }
        public int Property41 { get; set; }
        public int Property42 { get; set; }
        public int Property43 { get; set; }
        public int Property44 { get; set; }
        public int Property45 { get; set; }
        public int Property46 { get; set; }
        public int Property47 { get; set; }
        public int Property48 { get; set; }
        public int Property49 { get; set; }
        public int Property50 { get; set; }
        public int Property51 { get; set; }
        public int Property52 { get; set; }
        public int Property53 { get; set; }
        public int Property54 { get; set; }
        public int Property55 { get; set; }
        public int Property56 { get; set; }
        public int Property57 { get; set; }
        public int Property58 { get; set; }
        public int Property59 { get; set; }
        public int Property60 { get; set; }
        public int Property61 { get; set; }
        public int Property62 { get; set; }
        public int Property63 { get; set; }
        public int Property64 { get; set; }
    }
}
